/**
 * DO NOT EDIT THIS FILE!
 * File automatically generated by
 *   /home/workspace/gem5/build/ARM/SConscript:791
 */

#ifndef __ENUM__enums__DecoderFlavor__
#define __ENUM__enums__DecoderFlavor__

namespace gem5
{
namespace enums {
    enum DecoderFlavor
    {
        Generic = 0,
        Num_DecoderFlavor = 1
    };
    extern const char *DecoderFlavorStrings[Num_DecoderFlavor];
}; // enums

} // namespace gem5

#endif // __ENUM__enums__DecoderFlavor__
