/**
 * DO NOT EDIT THIS FILE!
 * File automatically generated by
 *   build_tools/sim_object_param_struct_hh.py:50
 */

#ifndef __PARAMS__GenericTimer__
#define __PARAMS__GenericTimer__

namespace gem5 {
class GenericTimer;
} // namespace gem5
#include <cstddef>
#include "base/types.hh"
#include <cstddef>
#include "params/SystemCounter.hh"
#include <cstddef>
#include "params/ArmPPI.hh"
#include <cstddef>
#include "params/ArmPPI.hh"
#include <cstddef>
#include "params/ArmPPI.hh"
#include <cstddef>
#include "params/ArmPPI.hh"
#include <cstddef>
#include "params/ArmSystem.hh"

#include "params/SimObject.hh"

namespace gem5
{
struct GenericTimerParams
    : public SimObjectParams
{
    gem5::GenericTimer * create() const;
    uint64_t cntfrq;
    gem5::SystemCounter * counter;
    gem5::ArmPPIGen * int_hyp;
    gem5::ArmPPIGen * int_phys_ns;
    gem5::ArmPPIGen * int_phys_s;
    gem5::ArmPPIGen * int_virt;
    gem5::ArmSystem * system;
};

} // namespace gem5

#endif // __PARAMS__GenericTimer__
