/**
 * DO NOT EDIT THIS FILE!
 * File automatically generated by
 *   /home/workspace/gem5/build/ARM/SConscript:791
 */

#ifndef __ENUM__enums__ArmLookupLevel__
#define __ENUM__enums__ArmLookupLevel__

namespace gem5
{
namespace enums {
    enum ArmLookupLevel
    {
        L0 = 0,
        L1 = 1,
        L2 = 2,
        L3 = 3,
        Num_ArmLookupLevel = 4
    };
    extern const char *ArmLookupLevelStrings[Num_ArmLookupLevel];
}; // enums

} // namespace gem5

#endif // __ENUM__enums__ArmLookupLevel__
